#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AWPrint.Droid.Resource", IsApplication=true)]

namespace AWPrint.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int primaryColor = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int primaryDarkColor = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int primaryLightColor = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int primaryTextColor = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int secondaryColor = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int secondaryDarkColor = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int secondaryLightColor = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int secondaryTextColor = 2130771975;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020001
			public const int anisoftware_logo_peque = 2130837505;
			
			// aapt resource value: 0x7F020000
			public const int FRESCOFRIO_AZUL = 2130837504;
			
			// aapt resource value: 0x7F020005
			public const int icon = 2130837509;
			
			// aapt resource value: 0x7F020002
			public const int ic_launcher = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int ic_printer = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int ic_settings = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int sliding_tabs = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int toolbar = 2130903041;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int Tabbar = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int Toolbar = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F050000
			public const int AppCompatDialogStyle = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int MainTheme = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int MainTheme_Base = 2131034114;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
